import 'package:flutter/material.dart';

class CustomColorScheme {
  static ColorScheme lightScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff5581e4),
      surfaceTint: Color(0xff65558f),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xffe9ddff),
      onPrimaryContainer: Color(0xff201047),
      secondary: Color(0xffb0d8d7),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff9ef2e4),
      onSecondaryContainer: Color(0xff00201c),
      tertiary: Color(0xff006a69),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff9cf1ef),
      onTertiaryContainer: Color(0xff002020),
      error: Colors.red,
      onError: Color(0xffffffff),
      errorContainer: Color(0xffffdad8),
      onErrorContainer: Color(0xff3b080a),
      surface: Color(0xfff1f8fd),
      onSurface: Color(0xff1d1d1d),
      onSurfaceVariant: Color(0xff3f484a),
      outline: Color(0xff6f797a),
      outlineVariant: Color(0xffbfc8ca),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff2b3133),
      inversePrimary: Color(0xffcfbdfe),
      primaryFixed: Color(0xffe9ddff),
      onPrimaryFixed: Color(0xff201047),
      primaryFixedDim: Color(0xffcfbdfe),
      onPrimaryFixedVariant: Color(0xff4d3d75),
      secondaryFixed: Color(0xff9ef2e4),
      onSecondaryFixed: Color(0xff00201c),
      secondaryFixedDim: Color(0xff82d5c8),
      onSecondaryFixedVariant: Color(0xff005048),
      tertiaryFixed: Color(0xff9cf1ef),
      onTertiaryFixed: Color(0xff002020),
      tertiaryFixedDim: Color(0xff80d5d3),
      onTertiaryFixedVariant: Color(0xff00504f),
      surfaceDim: Color(0xffd5dbdc),
      surfaceBright: Color(0xfff5fafb),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xffeff5f6),
      surfaceContainer: Color(0xffe9eff0),
      surfaceContainerHigh: Color(0xffe3e9ea),
      surfaceContainerHighest: Color(0xffdee3e5),
    );
  }

  static ColorScheme darkScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffcfbdfe),
      surfaceTint: Color(0xffcfbdfe),
      onPrimary: Color(0xff36275d),
      primaryContainer: Color(0xff4d3d75),
      onPrimaryContainer: Color(0xffe9ddff),
      secondary: Color(0xff82d5c8),
      onSecondary: Color(0xff003731),
      secondaryContainer: Color(0xff005048),
      onSecondaryContainer: Color(0xff9ef2e4),
      tertiary: Color(0xff80d5d3),
      onTertiary: Color(0xff003736),
      tertiaryContainer: Color(0xff00504f),
      onTertiaryContainer: Color(0xff9cf1ef),
      error: Color(0xffffb3af),
      onError: Color(0xff571d1d),
      errorContainer: Color(0xff733332),
      onErrorContainer: Color(0xffffdad8),
      surface: Color(0xff0e1415),
      onSurface: Color(0xffdee3e5),
      onSurfaceVariant: Color(0xffbfc8ca),
      outline: Color(0xff899294),
      outlineVariant: Color(0xff3f484a),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffdee3e5),
      inversePrimary: Color(0xff65558f),
      primaryFixed: Color(0xffe9ddff),
      onPrimaryFixed: Color(0xff201047),
      primaryFixedDim: Color(0xffcfbdfe),
      onPrimaryFixedVariant: Color(0xff4d3d75),
      secondaryFixed: Color(0xff9ef2e4),
      onSecondaryFixed: Color(0xff00201c),
      secondaryFixedDim: Color(0xff82d5c8),
      onSecondaryFixedVariant: Color(0xff005048),
      tertiaryFixed: Color(0xff9cf1ef),
      onTertiaryFixed: Color(0xff002020),
      tertiaryFixedDim: Color(0xff80d5d3),
      onTertiaryFixedVariant: Color(0xff00504f),
      surfaceDim: Color(0xff0e1415),
      surfaceBright: Color(0xff343a3b),
      surfaceContainerLowest: Color(0xff090f10),
      surfaceContainerLow: Color(0xff171d1e),
      surfaceContainer: Color(0xff1b2122),
      surfaceContainerHigh: Color(0xff252b2c),
      surfaceContainerHighest: Color(0xff303637),
    );
  }
}
